"""add availability exceptions

Revision ID: b07af10b4f1a
Revises: ab4e6e8d7b90
Create Date: 2026-08-16 22:18:29.460426
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b07af10b4f1a'
down_revision: str | None = 'ab4e6e8d7b90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(start_time IS NULL AND end_time IS NULL) OR (start_time IS NOT NULL AND end_time IS NOT NULL)', name='ck_availability_exceptions_time_pair'),
    sa.CheckConstraint('start_time < end_time', name='ck_availability_exceptions_time_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_availability_exceptions_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability_exceptions')
    # ### end Alembic commands ###
